In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../DATA/202_DT_B2_20210517105557.csv", encoding='cp949')
df.tail()

,구·군별,내외국인별,항목,단위,2015. 01 월,2015. 02 월,2015. 03 월,2015. 04 월,2015. 05 월,2015. 06 월,...,2020. 07 월,2020. 08 월,2020. 09 월,2020. 10 월,2020. 11 월,2020. 12 월,2021. 01 월,2021. 02 월,2021. 03 월,Unnamed: 79
2187,철마면,총인구,여자인구,명,3916,3897,3889,3897,3899,3916,...,4063.0,4056.0,4044.0,4033.0,4030.0,4031.0,4017.0,4001.0,3995.0,NaN
2188,철마면,한국인,세대수,세대,3521,3515,3508,3502,3506,3509,...,3852.0,3859.0,3863.0,3849.0,3860.0,3874.0,3867.0,3860.0,3851.0,NaN
2189,철마면,한국인,인구,명,8053,8008,7999,8007,7999,8019,...,8117.0,8110.0,8086.0,8056.0,8066.0,8080.0,8052.0,8026.0,8010.0,NaN
2190,철마면,한국인,남자인구,명,4173,4147,4147,4146,4138,4142,...,4086.0,4084.0,4072.0,4053.0,4065.0,4076.0,4061.0,4051.0,4041.0,NaN
2191,철마면,한국인,여자인구,명,3880,3861,3852,3861,3861,3877,...,4031.0,4026.0,4014.0,4003.0,4001.0,4004.0,3991.0,3975.0,3969.0,NaN

In [3]:
dong_file = open("../DATA/부산_행정동.txt")
dong_list = {}
gu_list = []
curr_dong = ''
for dong in dong_file:
    dong = dong.strip()
    if dong.find('·') == -1:
        curr_dong = dong
        gu_list.append(curr_dong)
    else:
        for don in dong.split(' · '):
            dong_list[don] = curr_dong

print(dong_list)

{'중앙동': '중구', '동광동': '중구', '대청동': '중구', '보수동': '중구', '부평동': '중구', '광복동': '중구', '남포동': '중구', '영주1동': '중구', '영주2동': '중구', '동대신1동': '서구', '동대신2동': '서구', '동대신3동': '서구', '서대신1동': '서구', '서대신3동': '서구', '서대신4동': '서구', '부민동': '서구', '아미동': '서구', '초장동': '서구', '충무동': '서구', '남부민1동': '서구', '남부민2동': '서구', '암남동': '서구', '초량1동': '동구', '초량2동': '동구', '초량3동': '동구', '초량6동': '동구', '수정1동': '동구', '수정2동': '동구', '수정4동': '동구', '수정5동': '동구', '좌천동': '동구', '범일1동': '동구', '범일2동': '동구', '범일5동': '동구', '남항동': '영도구', '영선1동': '영도구', '영선2동': '영도구', '신선동': '영도구', '봉래1동': '영도구', '봉래2동': '영도구', '청학1동': '영도구', '청학2동': '영도구', '동삼1동': '영도구', '동삼2동': '영도구', '동삼3동': '영도구', '부전1동': '부산진구', '부전2동': '부산진구', '연지동': '부산진구', '초읍동': '부산진구', '양정1동': '부산진구', '양정2동': '부산진구', '전포1동': '부산진구', '전포2동': '부산진구', '부암1동': '부산진구', '부암3동': '부산진구', '당감1동': '부산진구', '당감2동': '부산진구', '당감4동': '부산진구', '가야1동': '부산진구', '가야2동': '부산진구', '개금1동': '부산진구', '개금2동': '부산진구', '개금3동': '부산진구', '범천1동': '부산진구', '범천2동': '부산진구', '수민동': '동래구', '복산동': '동래구', '명륜동': '동래구', '온천1동': '동래구', '온천2동': '동래구', '온천3동': '동래구', '사직1동': '동래구', '사직2동': '동래구', '사직3동': '동래구', '안락1동': '동래구', '안락2동': '동래구', '명장1동': '동래구', '명장2동': '동래구', '대연1동': '남구', '대연3동': '남구', '대연4동': '남구', '대연5동': '남구', '대연6동': '남구', '용호1동': '남구', '용호2동': '남구', '용호3동': '남구', '용호4동': '남구', '용당동': '남구', '감만1동': '남구', '감만2동': '남구', '우암동': '남구', '문현1동': '남구', '문현2동': '남구', '문현3동': '남구', '문현4동': '남구', '민우모택동': '남구', '선자욱지동': '남구', '구포1동': '북구', '구포2동': '북구', '구포3동': '북구', '금곡동': '북구', '화명1동': '북구', '화명2동': '북구', '화명3동': '북구', '덕천1동': '북구', '덕천2동': '북구', '덕천3동': '북구', '만덕1동': '북구', '만덕2동': '북구', '만덕3동': '북구', '우1동': '해운대구', '우2동': '해운대구', '우3동': '해운대구', '중1동': '해운대구', '중2동': '해운대구', '좌1동': '해운대구', '좌2동': '해운대구', '좌3동': '해운대구', '좌4동': '해운대구', '송정동': '해운대구', '반여1동': '해운대구', '반여2동': '해운대구', '반여3동': '해운대구', '반여4동': '해운대구', '반송1동': '해운대구', '반송2동': '해운대구', '재송1동': '해운대구', '재송2동': '해운대구', '괴정1동': '사하구', '괴정2동': '사하구', '괴정3동': '사하구', '괴정4동': '사하구', '당리동': '사하구', '감천1동': '사하구', '감천2동': '사하구', '다대1동': '사하구', '다대2동': '사하구', '구평동': '사하구', '장림1동': '사하구', '장림2동': '사하구', '신평1동': '사하구', '신평2동': '사하구', '하단1동': '사하구', '하단2동': '사하구', '서1동': '금정구', '서2동': '금정구', '서3동': '금정구', '금사동': '금정구', '부곡1동': '금정구', '부곡2동': '금정구', '부곡3동': '금정구', '부곡4동': '금정구', '장전1동': '금정구', '장전2동': '금정구', '선두구동': '금정구', '청룡노포동': '금정구', '남산동': '금정구', '구서1동': '금정구', '구서2동': '금정구', '금성동': '금정구', '대저1동': '강서구', '대저2동': '강서구', '강동동': '강서구', '명지1동': '강서구', '명지2동': '강서구', '가락동': '강서구', '녹산동': '강서구', '가덕도동': '강서구', '거제1동': '연제구', '거제2동': '연제구', '거제3동': '연제구', '거제4동': '연제구', '연산1동': '연제구', '연산2동': '연제구', '연산3동': '연제구', '연산4동': '연제구', '연산5동': '연제구', '연산6동': '연제구', '연산8동': '연제구', '연산9동': '연제구', '남천1동': '수영구', '남천2동': '수영구', '수영동': '수영구', '망미1동': '수영구', '망미2동': '수영구', '광안1동': '수영구', '광안2동': '수영구', '광안3동': '수영구', '광안4동': '수영구', '민락동': '수영구', '삼락동': '사상구', '모라1동': '사상구', '모라3동': '사상구', '덕포1동': '사상구', '덕포2동': '사상구', '괘법동': '사상구', '감전동': '사상구', '주례1동': '사상구', '주례2동': '사상구', '주례3동': '사상구', '학장동': '사상구', '엄궁동': '사상구', '기장읍': '기장군', '장안읍': '기장군', '정관읍': '기장군', '일광면': '기장군', '철마면': '기장군'}

In [4]:
def makeDatesColumn():
    dates = []
    for year in range(2015, 2022):
        for month in range(1, 13):
            if year == 2021 and month > 3:
                continue
            dates.append("{0}. {1:0>2} 월".format(year, month))
    return dates

dates = makeDatesColumn()

In [5]:
# for date in dates:
#     df[date] = df[]
print(df['구·군별'].value_counts().index.to_list())

['선두구동', '하단2동', '범일4동', '대청동', '서대신2동', '반여1동', '강서구', '서3동', '서1동', '선동', '덕천3동', '남항동', '문현2동', '오륜동', '명륜1동', '부암1동', '괘법동', '반송3동', '용호1동', '사직1동', '양정3동', '토성동', '부곡3동', '남구', '덕포2동', '부전1동', '봉래4동', '온천2동', '명지동', '서대신1동', '괴정1동', '서대신3동', '초량2동', '좌1동', '대연5동', '범일1동', '감전2동', '수정1동', '장전3동', '부산진구', '아미2동', '신선1동', '신선동', '남부민1동', '기장군', '대연1동', '영선2동', '서2동', '초장동', '반여2동', '일광면', '수영구', '영주2동', '연산5동', '안락2동', '양정2동', '청학1동', '사직2동', '동대신2동', '청룡동', '초량6동', '수정4동', '부평동', '대저1동', '부산광역시', '사상구', '감만1동', '수정2동', '영도구', '당감4동', '감전1동', '광안2동', '대교동', '주례2동', '명지2동', '명장2동', '좌천3동', '초량4동', '괴정3동', '가야3동', '반송1동', '북구', '봉래1동', '명륜동', '좌동', '충무동', '다대1동', '온천3동', '암남동', '모라2동', '금곡동', '정관읍', '부곡4동', '강동동', '좌천1동', '기장읍', '화명2동', '가덕도동', '광안1동', '범일2동', '안락1동', '연지동', '봉래3동', '복산동', '장전2동', '금사회동동', '동삼3동', '당감1동', '우암2동', '개금2동', '문현4동', '초량1동', '범천2동', '좌3동', '수영동', '범일5동', '연산6동', '만덕2동', '철마면', '범일6동', '전포1동', '우암동', '좌천4동', '광안3동', '만덕3동', '연산2동', '양정1동', '모라3동', '영주1동', '아미동', '덕천2동', '대연3동', '대연4동', '모라1동', '수민동', '화명3동', '동구', '대평동', '부암3동', '전포3동', '주례1동', '당감3동', '부전2동', '신선3동', '반송2동', '하단1동', '부곡2동', '당감2동', '명지1동', '남포동', '초량3동', '좌2동', '대연2동', '해운대구', '청학2동', '수정3동', '문현1동', '장전1동', '양정4동', '거제1동', '감만2동', '망미2동', '학장동', '중1동', '신평2동', '재송1동', '덕포1동', '가야2동', '두구동', '거제2동', '전포4동', '개금3동', '반여3동', '삼락동', '우3동', '남천2동', '보수동', '노포동', '화명동', '동대신3동', '용당동', '부암2동', '감천2동', '신선2동', '다대2동', '대저2동', '구포3동', '구서2동', '용호4동', '대연6동', '사직3동', '우1동', '화명1동', '서대신4동', '가야1동', '문현3동', '명장1동', '서4동', '연산8동', '남산동', '연산3동', '명륜2동', '동삼1동', '가락동', '연산4동', '주례3동', '우암1동', '온천1동', '만덕1동', '당리동', '수정5동', '용호2동', '중앙동', '민락동', '연제구', '감천1동', '반여4동', '감전동', '연산7동', '전포2동', '녹산동', '영선1동', '봉래2동', '금성동', '개금1동', '엄궁동', '신평1동', '구평동', '부곡1동', '장림2동', '광복동', '구포2동', '보수2동', '용호3동', '범전동', '남부민3동', '석대동', '구포1동', '금정구', '남부민2동', '연산1동', '부민동', '좌천동', '괴정2동', '덕천1동', '연산9동', '우2동', '부용동', '광안4동', '범천4동', '망미1동', '거제4동', '초읍동', '좌천2동', '범천1동', '거제3동', '좌4동', '문현5동', '동삼2동', '청룡노포동', '동대신1동', '구서1동', '장림1동', '장안읍', '중구', '서구', '재송2동', '남천1동', '송정동', '동광동', '중2동', '동래구', '사하구', '괴정4동']

In [6]:
group_by_data = {}
for i in range(0, len(df.index), 8):
    gu = df["구·군별"][i]
    group_by_data[gu] = df.iloc[i: i + 8, :-1]
group_by_data['장전1동']

,구·군별,내외국인별,항목,단위,2015. 01 월,2015. 02 월,2015. 03 월,2015. 04 월,2015. 05 월,2015. 06 월,...,2020. 06 월,2020. 07 월,2020. 08 월,2020. 09 월,2020. 10 월,2020. 11 월,2020. 12 월,2021. 01 월,2021. 02 월,2021. 03 월
1616,장전1동,총인구,세대수,세대,8786,8841,8911,8874,8880,8859,...,10297.0,10311.0,10350.0,10377.0,10364.0,10392.0,10382.0,10265.0,10396.0,10579.0
1617,장전1동,총인구,인구,명,19776,19781,19896,19814,19819,19750,...,19578.0,19521.0,19506.0,19517.0,19427.0,19428.0,19347.0,19183.0,19283.0,19467.0
1618,장전1동,총인구,남자인구,명,10010,10009,10047,10027,10022,9978,...,9935.0,9902.0,9912.0,9914.0,9889.0,9875.0,9838.0,9766.0,9886.0,9994.0
1619,장전1동,총인구,여자인구,명,9766,9772,9849,9787,9797,9772,...,9643.0,9619.0,9594.0,9603.0,9538.0,9553.0,9509.0,9417.0,9397.0,9473.0
1620,장전1동,한국인,세대수,세대,8786,8841,8911,8874,8880,8859,...,10297.0,10311.0,10350.0,10377.0,10364.0,10392.0,10382.0,10265.0,10396.0,10579.0
1621,장전1동,한국인,인구,명,18634,18656,18693,18617,18615,18510,...,18092.0,18064.0,18075.0,18039.0,17960.0,17972.0,17902.0,17771.0,17879.0,18036.0
1622,장전1동,한국인,남자인구,명,9442,9445,9459,9443,9430,9371,...,9268.0,9246.0,9268.0,9247.0,9219.0,9209.0,9186.0,9121.0,9243.0,9346.0
1623,장전1동,한국인,여자인구,명,9192,9211,9234,9174,9185,9139,...,8824.0,8818.0,8807.0,8792.0,8741.0,8763.0,8716.0,8650.0,8636.0,8690.0

In [7]:
final_data = pd.DataFrame(index = list(dong_list.keys()) + gu_list)
final_data['세대수'] = None
final_data['인구수'] = None
final_data

      세대수   인구수
중앙동  None  None
동광동  None  None
대청동  None  None
보수동  None  None
부평동  None  None
..    ...   ...
강서구  None  None
연제구  None  None
수영구  None  None
사상구  None  None
기장군  None  None

[223 rows x 2 columns]

In [8]:
from sklearn.linear_model import LinearRegression
predictDate = 202105
# 202105 예측결과
for dong_population in group_by_data:
    # print(dong_population)
    X = []
    y = []
    df = group_by_data[dong_population][(group_by_data[dong_population]['항목'] == "세대수") & (group_by_data[dong_population]['내외국인별'] == "총인구")].iloc[:, 4:]
    df = df.dropna()
    # print(df)
    # print(df.dtypes)
    if not df.empty:
        for col in df:
            if df[col].values[0] != '-':
                # print(int(col.split('. ')[0] + col.split(' ')[1]))
                X.append(int(col.split('. ')[0] + col.split(' ')[1]))
                # print(df[col].values[0])
                # print(df[col].values[0])
                y.append(int(df[col].values[0]))
    if X:
        X = np.array(X)
        y = np.array(y)
        reg = LinearRegression().fit(X.reshape(-1, 1), y)
        predict = reg.predict((np.array([[predictDate]])))[0]
        final_data['세대수'][dong_population] = predict
        print(dong_population, predict)
    else:
        print(dong_population, "NO")

부산광역시 1527730.3187716752
중구 23369.31540688471
중앙동 1556.6676842971356
동광동 1866.204541920546
대청동 3490.663881729386
보수동 5829.283647356671
부평동 2675.9375836528707
광복동 645.5655795204511
남포동 680.9869025634762
영주1동 2958.9369839260326
영주2동 3665.0686019181303
보수2동 NO
서구 52969.80571559052
동대신1동 2222.4138128414343
동대신2동 3632.545091054315
동대신3동 3545.561003131119
서대신1동 5651.381043411326
서대신3동 3581.2805935325014
서대신4동 3209.6720952201576
부민동 4313.00876444162
아미동 4024.105543910875
초장동 2713.4366944608482
충무동 5786.832634478284
남부민1동 2703.5485447618194
남부민2동 5030.14706321471
암남동 6555.87283113139
서대신2동 NO
부용동 NO
토성동 NO
아미2동 NO
남부민3동 NO
동구 45162.14767028275
초량1동 2739.150435078069
초량2동 3353.7535251097843
초량3동 5050.544815240661
초량6동 3236.4356720961805
수정1동 1979.67398882196
수정2동 4990.34723681421
수정4동 2322.2749486150715
수정5동 2814.146722879188
좌천동 5494.412822509839
범일1동 7408.593520827359
범일2동 4679.586909695237
범일5동 2303.542031825149
초량4동 NO
수정3동 NO
좌천1동 NO
좌천2동 NO
좌천3동 NO
좌천4동 NO
범일4동 NO
범일6동 NO
영도구 54493.27277758531
남항동 5570.223784469534
영선1동 1918.8426293147095
영선2동 3970.265550063981
신선동 4859.335073936876
봉래1동 3570.774450018049
봉래2동 2381.1524896193296
청학1동 3268.4835576869955
청학2동 8020.523926624017
동삼1동 13092.717536383745
동삼2동 1873.0109131096451
동삼3동 5967.942866358404
대교동 NO
대평동 NO
신선1동 NO
신선2동 NO
신선3동 NO
봉래3동 NO
봉래4동 NO
부산진구 169550.62167634373
부전1동 9465.789594578207
부전2동 5572.6143383118615
연지동 8276.04097358344
초읍동 9418.390750893304
양정1동 9150.020196268451
양정2동 7864.310331860208
전포1동 10698.28665761894
전포2동 11451.770004641556
부암1동 9796.590674891544
부암3동 6666.29329252569
당감1동 10459.985975618227
당감2동 4408.1569303761935
당감4동 5203.871751526007
가야1동 10293.586889575094
가야2동 7087.1136095084075
개금1동 9150.143787425244
개금2동 5027.93404768125
개금3동 12372.931151731322
범천1동 7182.984920670744
범천2동 11205.769854010548
범천4동 NO
전포3동 NO
범전동 NO
당감3동 NO
가야3동 NO
양정3동 NO
양정4동 NO
전포4동 NO
부암2동 NO
동래구 114156.66169499699
수민동 13284.973296570766
복산동 4921.097950517986
명륜동 9745.075364952325
온천1동 10245.006089769799
온천2동 5726.168752061785
온천3동 17077.16889192653
사직1동 4785.083400748612
사직2동 10026.584418291925
사직3동 7506.016852820874
안락1동 6843.9564917895095
안락2동 11366.97381239725
명장1동 5927.639790179002
명장2동 6700.916582970822
명륜1동 NO
명륜2동 NO
남구 118357.73667896469
대연1동 9147.572508582729
대연3동 15105.187089514584
대연4동 5626.375826558564
대연5동 7942.643859391916
대연6동 6736.472437207121
용호1동 17293.34462544811
용호2동 6617.512162479223
용호3동 5681.768004134032
용호4동 3826.6909387476
용당동 3338.782900298378
감만1동 6457.560251502306
감만2동 3336.4470538816704
우암동 5687.300386754214
문현1동 6038.8128333045315
문현2동 5262.152370883618
문현3동 6040.001845333056
문현4동 4219.111584942904
우암1동 NO
우암2동 NO
대연2동 NO
문현5동 NO
북구 121277.22489667963
구포1동 7495.057952295814
구포2동 11981.173496709875
구포3동 9235.134796725964
금곡동 18260.90723223581
화명1동 14900.048209814937
화명2동 6005.48039868605
화명3동 10665.458809458103
덕천1동 6624.130462100264
덕천2동 6614.079117473317
덕천3동 5766.322867683099
만덕1동 4929.573240822239
만덕2동 11367.713136472506
만덕3동 7432.145176201469
화명동 NO
해운대구 170647.9818219263
우1동 8257.4876158447
우2동 11910.17442671489
우3동 10716.283964397502
중1동 10696.095925712434
중2동 7835.71980623086
좌1동 7640.30663927424
좌2동 14007.455087256385
좌3동 6365.913942054408
좌4동 8517.748184334492
송정동 5183.59241260984
반여1동 12488.636888562236
반여2동 6874.851745583663
반여3동 4699.564679796575
반여4동 5967.1274267382105
반송1동 8730.075174637139
반송2동 12172.81076189378
재송1동 15116.232648699079
재송2동 11509.211555008631
반송3동 NO
좌동 NO
석대동 NO
사하구 140163.04218929587
괴정1동 8956.037747404422
괴정2동 6197.9163464431185
괴정3동 6760.67401577608
괴정4동 5166.324896175589
당리동 11641.059521253497
하단1동 10253.031432489573
하단2동 12476.953958973172
신평1동 8691.453658550774
신평2동 6770.324462585908
장림1동 5229.191046995053
장림2동 11796.31083813106
다대1동 16896.551358229466
다대2동 12215.15182460695
구평동 5207.39026826038
감천1동 8373.511673132336
감천2동 3531.1591402882477
금정구 108950.43776203459
서1동 3446.2794643275556
서2동 5122.945520081092
서3동 5947.391520346107
금사회동동 4315.325726468822
부곡1동 4524.231014990612
부곡2동 7319.153294032876
부곡3동 7253.284073070623
부곡4동 6224.644856504237
장전1동 10423.031222801423
장전2동 10008.368790072389
선두구동 1277.84379219322
청룡노포동 4494.3122086851945
남산동 14166.656701555097
구서1동 7994.411885266076
구서2동 13520.042403461732
금성동 489.08661027634207
장전3동 NO
서4동 NO
오륜동 NO
선동 NO
두구동 NO
노포동 NO
청룡동 NO
강서구 59960.81372835394
대저1동 3733.8154430290015
대저2동 3716.1270543217106
강동동 2489.676465308352
명지1동 NO
명지2동 NO
가락동 1432.6308217760234
녹산동 16238.70169111411
가덕도동 2268.221618228461
명지동 NO
연제구 92456.61483284552
거제1동 11422.68904878915
거제2동 3971.4709146857494
거제3동 4792.532504562871
거제4동 4229.0616490050525
연산1동 7152.321893205401
연산2동 8371.42251330649
연산3동 3481.1253899773583
연산4동 8978.129972246184
연산5동 10477.985297608655
연산6동 8243.297416546848
연산8동 6490.357466018468
연산9동 14846.220766893326
연산7동 NO
수영구 84215.71193434624
남천1동 6267.143219152185
남천2동 4649.3478164427215
수영동 7878.569057013228
망미1동 12160.91394812474
망미2동 5220.450996456071
광안1동 13976.832949648495
광안2동 9538.023155044066
광안3동 6052.022767972434
광안4동 5239.0045759584755
민락동 13233.403448533732
사상구 97219.95975213297
삼락동 3184.7612347240065
모라1동 11962.359529482637
모라3동 6888.927344385753
덕포1동 4038.959889058082
덕포2동 5741.770383892039
괘법동 12026.167888732976
감전동 7292.5106544000955
주례1동 6560.9492491276615
주례2동 11067.462609222479
주례3동 5701.620649136134
학장동 12090.512119888168
엄궁동 10663.95820008294
모라2동 NO
감전1동 NO
감전2동 NO
기장군 74778.97023340967
기장읍 25888.76308133325
장안읍 4779.322812013153
정관읍 33296.22947135614
일광면 7272.367265767185
철마면 3542.287602939061

In [9]:

predictDate = 202105
# 202105 예측결과
for dong_population in group_by_data:
    # print(dong_population)
    X = []
    y = []
    df = group_by_data[dong_population][(group_by_data[dong_population]['항목'] == "인구") & (group_by_data[dong_population]['내외국인별'] == "총인구")].iloc[:, 4:]
    df = df.dropna()
    # print(df)
    # print(df.dtypes)
    if not df.empty:
        for col in df:
            if df[col].values[0] != '-':
                # print(int(col.split('. ')[0] + col.split(' ')[1]))
                X.append(int(col.split('. ')[0] + col.split(' ')[1]))
                # print(df[col].values[0])
                # print(df[col].values[0])
                y.append(int(df[col].values[0]))
    if X:
        X = np.array(X)
        y = np.array(y)
        reg = LinearRegression().fit(X.reshape(-1, 1), y)
        predict = reg.predict((np.array([[predictDate]])))[0]
        final_data['인구수'][dong_population] = predict
        print(dong_population, predict)
    else:
        print(dong_population, "NO")

부산광역시 3433666.1138185933
중구 42977.197314933874
중앙동 2730.361468849762
동광동 3098.727610588132
대청동 6488.369945789687
보수동 10777.85392392741
부평동 4824.404822507553
광복동 1069.156620038193
남포동 1244.6228798937227
영주1동 5211.766901932337
영주2동 7531.933141407033
보수2동 NO
서구 108057.02272607433
동대신1동 4371.723891457077
동대신2동 7570.597135479795
동대신3동 7001.639004292985
서대신1동 12648.938970241928
서대신3동 8846.702694754902
서대신4동 8238.787410720426
부민동 8447.255233092365
아미동 6976.311095973477
초장동 4595.699968187371
충무동 11005.517677540076
남부민1동 5100.5755604053265
남부민2동 9659.081253013457
암남동 13594.192830915097
서대신2동 NO
부용동 NO
토성동 NO
아미2동 NO
남부민3동 NO
동구 88976.47343018511
초량1동 5756.622732660442
초량2동 6106.72409404401
초량3동 10234.461449125316
초량6동 6314.183398330351
수정1동 4144.808739482658
수정2동 9742.921575060376
수정4동 4174.365250555624
수정5동 5599.491302807408
좌천동 11181.251968475
범일1동 14476.599119783146
범일2동 8983.930412750517
범일5동 4815.35827570073
초량4동 NO
수정3동 NO
좌천1동 NO
좌천2동 NO
좌천3동 NO
좌천4동 NO
범일4동 NO
범일6동 NO
영도구 113919.64325081278
남항동 11366.93507885427
영선1동 4176.645371245366
영선2동 8826.49917041586
신선동 8902.277274824795
봉래1동 7475.6711888477585
봉래2동 4578.718039862113
청학1동 6759.177781070583
청학2동 18501.80664006516
동삼1동 29263.024031391833
동삼2동 3729.5530256335915
동삼3동 10339.335648602108
대교동 NO
대평동 NO
신선1동 NO
신선2동 NO
신선3동 NO
봉래3동 NO
봉래4동 NO
부산진구 354614.57799788564
부전1동 15060.261483403388
부전2동 10183.809409681824
연지동 20014.314882413484
초읍동 20888.638466306613
양정1동 20341.835014149197
양정2동 12945.884549211012
전포1동 18655.219307617474
전포2동 21680.133668104623
부암1동 23529.018367532204
부암3동 17064.91074483702
당감1동 23939.3674044325
당감2동 10154.973172397396
당감4동 11810.165220240713
가야1동 20459.792718503857
가야2동 16713.47545691603
개금1동 18048.95790202217
개금2동 11348.910423263209
개금3동 29450.971175456652
범천1동 12090.22916263272
범천2동 22802.645334789995
범천4동 NO
전포3동 NO
범전동 NO
당감3동 NO
가야3동 NO
양정3동 NO
양정4동 NO
전포4동 NO
부암2동 NO
동래구 270493.90133317956
수민동 32305.38768074503
복산동 10154.477583985776
명륜동 26162.782333241543
온천1동 19067.00951751042
온천2동 13951.539587277919
온천3동 38727.463439657586
사직1동 10912.251249186811
사직2동 29351.546009469377
사직3동 17699.8956002763
안락1동 14875.34954590362
안락2동 28424.829093832523
명장1동 13410.510681866901
명장2동 15450.859010225526
명륜1동 NO
명륜2동 NO
남구 275799.2279411936
대연1동 17851.358357250458
대연3동 35509.52207928384
대연4동 12944.611909330706
대연5동 17622.17092895438
대연6동 18068.151878493838
용호1동 46265.89350373857
용호2동 17163.54242279101
용호3동 12508.459160701837
용호4동 8767.586784360115
용당동 8118.644745655358
감만1동 14057.189808364608
감만2동 7122.304119755048
우암동 12748.330231497064
문현1동 14302.396210807841
문현2동 9209.178373478033
문현3동 14562.544714219985
문현4동 8977.342712511541
우암1동 NO
우암2동 NO
대연2동 NO
문현5동 NO
북구 287374.52632492036
구포1동 14957.934071019292
구포2동 26426.940404058085
구포3동 21630.13396701077
금곡동 39193.2372059396
화명1동 43742.59387400199
화명2동 14991.629534817068
화명3동 30356.158185756067
덕천1동 12534.91262319428
덕천2동 12247.33522427897
덕천3동 11095.053798195207
만덕1동 11737.900427668588
만덕2동 29438.44712470856
만덕3동 19022.249884272227
화명동 NO
해운대구 404646.81470936537
우1동 15491.070255163126
우2동 31663.691267684044
우3동 28956.32178510129
중1동 24713.328929958778
중2동 17640.993154734373
좌1동 18271.198876081267
좌2동 32504.50019285688
좌3동 16503.095352274366
좌4동 23514.252731053624
송정동 10517.25954754879
반여1동 33613.75842635613
반여2동 13129.036089163274
반여3동 8963.737633382203
반여4동 16138.15382754698
반송1동 16731.21696130396
반송2동 24097.137621483766
재송1동 40379.64135116828
재송2동 25559.722673590528
반송3동 NO
좌동 NO
석대동 NO
사하구 318351.9566793572
괴정1동 20705.919916219224
괴정2동 14201.332984162262
괴정3동 13296.49669203686
괴정4동 11374.540692114038
당리동 27625.756254906068
하단1동 21859.51304358279
하단2동 26013.58710029407
신평1동 18671.407086584208
신평2동 16593.45542080159
장림1동 12093.744727752754
장림2동 28176.113078034075
다대1동 40268.28660812881
다대2동 28198.570043811807
구평동 13539.452594631352
감천1동 19422.82130921888
감천2동 6310.959127077367
금정구 239469.22554370016
서1동 5938.326425585663
서2동 9831.00016882061
서3동 11543.7844834149
금사회동동 8512.677485976717
부곡1동 8608.958727532183
부곡2동 16852.04046276922
부곡3동 17137.035761977517
부곡4동 13278.013198500965
장전1동 19480.5797005379
장전2동 24198.313585767988
선두구동 2379.051692560053
청룡노포동 10186.305482237047
남산동 30838.44148071832
구서1동 20040.471656082605
구서2동 33935.80034130521
금성동 1101.2820620094135
장전3동 NO
서4동 NO
오륜동 NO
선동 NO
두구동 NO
노포동 NO
청룡동 NO
강서구 148849.57091427222
대저1동 6704.624063159688
대저2동 7376.506894876016
강동동 4223.468564063427
명지1동 NO
명지2동 NO
가락동 2613.3703539523412
녹산동 39246.22827427508
가덕도동 3671.602983404169
명지동 NO
연제구 209797.2984068032
거제1동 29955.55542113213
거제2동 11055.461767464876
거제3동 10418.72382288822
거제4동 10921.145506152418
연산1동 17172.66316767926
연산2동 18950.36680020066
연산3동 6927.062871715054
연산4동 17284.852568775663
연산5동 17610.59595520282
연산6동 17328.39769939403
연산8동 15428.256287265307
연산9동 36744.216538933455
연산7동 NO
수영구 177663.16432157508
남천1동 14080.039262197504
남천2동 11645.215983248549
수영동 15003.108488871309
망미1동 27816.22025251758
망미2동 11587.97738952015
광안1동 26760.24666608352
광안2동 19498.85912765219
광안3동 10205.532584312663
광안4동 11302.746477470035
민락동 29763.218089701608
사상구 216133.0814566929
삼락동 6394.300775723939
모라1동 28131.84966002498
모라3동 10852.777215282433
덕포1동 8677.138594734017
덕포2동 13372.329665972502
괘법동 22977.815248110535
감전동 14301.013917061617
주례1동 16153.952594647737
주례2동 24333.68191228027
주례3동 13370.162388081895
학장동 29350.612738833064
엄궁동 28217.446745937923
모라2동 NO
감전1동 NO
감전2동 NO
기장군 176542.4314676486
기장읍 55202.48358957708
장안읍 9115.793406630706
정관읍 87436.91416734643
일광면 16303.517509935424
철마면 8483.722794158632

In [10]:
print(final_data.index.to_list())

['중앙동', '동광동', '대청동', '보수동', '부평동', '광복동', '남포동', '영주1동', '영주2동', '동대신1동', '동대신2동', '동대신3동', '서대신1동', '서대신3동', '서대신4동', '부민동', '아미동', '초장동', '충무동', '남부민1동', '남부민2동', '암남동', '초량1동', '초량2동', '초량3동', '초량6동', '수정1동', '수정2동', '수정4동', '수정5동', '좌천동', '범일1동', '범일2동', '범일5동', '남항동', '영선1동', '영선2동', '신선동', '봉래1동', '봉래2동', '청학1동', '청학2동', '동삼1동', '동삼2동', '동삼3동', '부전1동', '부전2동', '연지동', '초읍동', '양정1동', '양정2동', '전포1동', '전포2동', '부암1동', '부암3동', '당감1동', '당감2동', '당감4동', '가야1동', '가야2동', '개금1동', '개금2동', '개금3동', '범천1동', '범천2동', '수민동', '복산동', '명륜동', '온천1동', '온천2동', '온천3동', '사직1동', '사직2동', '사직3동', '안락1동', '안락2동', '명장1동', '명장2동', '대연1동', '대연3동', '대연4동', '대연5동', '대연6동', '용호1동', '용호2동', '용호3동', '용호4동', '용당동', '감만1동', '감만2동', '우암동', '문현1동', '문현2동', '문현3동', '문현4동', '민우모택동', '선자욱지동', '구포1동', '구포2동', '구포3동', '금곡동', '화명1동', '화명2동', '화명3동', '덕천1동', '덕천2동', '덕천3동', '만덕1동', '만덕2동', '만덕3동', '우1동', '우2동', '우3동', '중1동', '중2동', '좌1동', '좌2동', '좌3동', '좌4동', '송정동', '반여1동', '반여2동', '반여3동', '반여4동', '반송1동', '반송2동', '재송1동', '재송2동', '괴정1동', '괴정2동', '괴정3동', '괴정4동', '당리동', '감천1동', '감천2동', '다대1동', '다대2동', '구평동', '장림1동', '장림2동', '신평1동', '신평2동', '하단1동', '하단2동', '서1동', '서2동', '서3동', '금사동', '부곡1동', '부곡2동', '부곡3동', '부곡4동', '장전1동', '장전2동', '선두구동', '청룡노포동', '남산동', '구서1동', '구서2동', '금성동', '대저1동', '대저2동', '강동동', '명지1동', '명지2동', '가락동', '녹산동', '가덕도동', '거제1동', '거제2동', '거제3동', '거제4동', '연산1동', '연산2동', '연산3동', '연산4동', '연산5동', '연산6동', '연산8동', '연산9동', '남천1동', '남천2동', '수영동', '망미1동', '망미2동', '광안1동', '광안2동', '광안3동', '광안4동', '민락동', '삼락동', '모라1동', '모라3동', '덕포1동', '덕포2동', '괘법동', '감전동', '주례1동', '주례2동', '주례3동', '학장동', '엄궁동', '기장읍', '장안읍', '정관읍', '일광면', '철마면', '중구', '서구', '동구', '영도구', '부산진구', '동래구', '남구', '북구', '해운대구', '사하구', '금정구', '강서구', '연제구', '수영구', '사상구', '기장군']

In [11]:
price = pd.read_csv("../DATA/매출액.csv")
price = price.iloc[:, 1:]
floating_popu = pd.read_csv("../DATA/유동인구.csv")
floating_popu = floating_popu.iloc[:, 1:]

In [12]:
for col in price.columns:
    if col != 'loc':
        final_data[col] = None
for col in floating_popu.columns:
    if col != 'loc':
        final_data[col] = None

In [13]:
for row in price.iterrows():
    dong = price['loc'][row[0]].split(' ')[2]
    for col in price.columns:
        if col != 'loc':
            final_data[col][dong] = price[col][row[0]]

In [14]:
for row in floating_popu.iterrows():
    dong = floating_popu['loc'][row[0]].split(' ')[2]
    for col in floating_popu.columns:
        if col != 'loc':
            final_data[col][dong] = floating_popu[col][row[0]]

In [15]:
final_data['등급'] = None
file = open("../DATA/answer.txt", 'r')
for line in file:
    line = line.strip()
    dong, grade = line.split(':')
    
    final_data['등급'][dong] = grade
    print(dong, grade)

부전2동 2등급
기장읍 4등급
우2동 2등급
부전1동 3등급
범일2동 3등급
중1동 2등급
정관읍 4등급
우1동 2등급
대연3동 3등급
좌2동 4등급
괘법동 4등급
녹산동 5등급
남천1동 3등급
좌1동 2등급
광복동 2등급
하단2동 5등급
범천1동 3등급
전포1동 3등급
민락동 4등급
중앙동 3등급
용호1동 4등급
연산9동 3등급
반여1동 3등급
연산5동 3등급
온천1동 4등급
재송1동 3등급
당리동 4등급
명지동 5등급
감전동 5등급
남산동 3등급
다대1동 4등급
모라1동 3등급
수민동 4등급
안락2동 3등급
남포동 3등급
수영동 4등급
화명3동 4등급
연산4동 2등급
광안2동 4등급
명륜동 4등급
구포1동 5등급
온천3동 2등급
하단1동 4등급
덕천2동 3등급
대연1동 3등급
양정1동 2등급
온천2동 4등급
동삼1동 4등급
구서2동 2등급
부평동 2등급
거제1동 3등급
거제1동 3등급
연산1동 3등급
초량3동 4등급
광안1동 3등급
엄궁동 3등급
장안읍 5등급
장림2동 5등급
일광면 4등급
초읍동 3등급
전포2동 4등급
안락1동 3등급
구서1동 4등급
광안3동 2등급
개금1동 4등급
학장동 4등급
망미1동 4등급
명지1동 5등급
대연5동 4등급
대저2동 4등급
남항동 4등급
사직2동 4등급
대저1동 5등급
괴정3동 5등급
구포2동 5등급
장전1동 3등급
반송1동 4등급
괴정1동 4등급
반송2동 4등급
서3동 5등급
신평1동 4등급
재송2동 3등급
가야1동 4등급
연산2동 3등급
당감1동 4등급
사직1동 3등급
부곡3동 4등급
주례2동 4등급
양정2동 4등급
반여2동 4등급
금곡동 4등급
장전2동 3등급
장림1동 5등급
송정동 5등급
만덕2동 4등급
다대2동 4등급
연산8동 4등급
충무동 4등급
사직3동 4등급
남천2동 2등급
용호3동 3등급
명장1동 4등급
수정2동 5등급
광안4동 3등급
용호2동 4등급
좌4동 3등급
개금3동 4등급
연산6동 4등급
감천1동 4등급
화명1동 3등급
중2동 4등급
신평2동 4등급
가야2동 4등급
서대신1동 3등급
암남동 5등급
장전3동 5등급
거제3동 3등급
괴정4동 4등급
덕천1동 4등급
덕포2동 4등급
부암1동 3등급
구포3동 5등급
거제2동 3등급
금사동 5등급
연지동 4등급
청학2동 5등급
복산동 4등급
부암3동 4등급
주례3동 4등급
초량1동 4등급
초량2동 4등급
범일1동 3등급
만덕3동 4등급
대연4동 4등급
문현3동 3등급
봉래1동 4등급
부곡2동 4등급
영선1동 4등급
보수동 5등급
서2동 3등급
화명2동 4등급
당감4동 4등급
우3동 3등급
문현1동 4등급
주례1동 4등급
감만1동 4등급
괴정2동 4등급
강동동 5등급
삼락동 4등급
덕포1동 4등급
용당동 5등급
대연6동 5등급
범천2동 4등급
문현2동 4등급
망미2동 4등급
명장2동 5등급
동대신3동 3등급
대청동 4등급
문현4동 3등급
부민동 3등급
부곡4동 3등급
좌3동 3등급
반여3동 5등급
철마면 5등급
청룡노포동 4등급
좌천동 4등급
구평동 5등급
우암동 4등급
부곡1동 4등급
명지2동 2등급
영선2동 4등급
만덕1동 4등급
동광동 4등급
서대신3동 5등급
영주1동 4등급
동대신2동 5등급
용호4동 4등급
청학1동 5등급
연산3동 4등급
동삼2동 5등급
선두구동
당감2동 4등급
가덕도동 5등급
서1동 5등급
덕천3동 5등급
감천2동 5등급
남부민1동 5등급
동대신1동 5등급
반여4동 4등급
남부민2동 5등급
가락동 5등급
거제4동 4등급
개금2동 3등급
서대신4동 5등급
아미동 5등급
감만2동 4등급
초량6동 5등급
수정1동 4등급
동삼3동 5등급
영주2동 5등급
신선동 5등급
수정4동 5등급
범일5동 5등급
봉래2동 5등급
모라3동 5등급
수정5동 5등급
금사회동동 5등급
초장동 5등급

In [18]:
for gu in final_data.index.to_list():
    # print(gu)
    if gu[-1] == '구' or gu[-1] == '군':
        print(final_data.loc[gu, :])

세대수               23369.315407
인구수               42977.197315
202003_maxAmt             None
202003_minAmt             None
202003_saleAmt            None
                      ...
thur                      None
tues                      None
wed                       None
weekend                   None
등급                        None
Name: 중구, Length: 64, dtype: object
세대수                52969.805716
인구수               108057.022726
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 서구, Length: 64, dtype: object
세대수               45162.14767
인구수               88976.47343
202003_maxAmt            None
202003_minAmt            None
202003_saleAmt           None
                     ...
thur                     None
tues                     None
wed                      None
weekend                  None
등급                       None
Name: 동구, Length: 64, dtype: object
세대수                54493.272778
인구수               113919.643251
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 영도구, Length: 64, dtype: object
세대수               169550.621676
인구수               354614.577998
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 부산진구, Length: 64, dtype: object
세대수               114156.661695
인구수               270493.901333
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 동래구, Length: 64, dtype: object
세대수               118357.736679
인구수               275799.227941
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 남구, Length: 64, dtype: object
세대수               121277.224897
인구수               287374.526325
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 북구, Length: 64, dtype: object
세대수               170647.981822
인구수               404646.814709
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 해운대구, Length: 64, dtype: object
세대수               140163.042189
인구수               318351.956679
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 사하구, Length: 64, dtype: object
세대수               108950.437762
인구수               239469.225544
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 금정구, Length: 64, dtype: object
세대수                59960.813728
인구수               148849.570914
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 강서구, Length: 64, dtype: object
세대수                92456.614833
인구수               209797.298407
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 연제구, Length: 64, dtype: object
세대수                84215.711934
인구수               177663.164322
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 수영구, Length: 64, dtype: object
세대수                97219.959752
인구수               216133.081457
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 사상구, Length: 64, dtype: object
세대수                74778.970233
인구수               176542.431468
202003_maxAmt              None
202003_minAmt              None
202003_saleAmt             None
                      ...
thur                       None
tues                       None
wed                        None
weekend                    None
등급                         None
Name: 기장군, Length: 64, dtype: object

In [17]:
len(final_data)

223

In [19]:
df = pd.read_csv('../DATA/소상공인시장진흥공단_상가(상권)정보_부산_202012.csv')
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,17175332,정성밥상,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2.635010e+24,NaN,부산광역시 해운대구 해운대로 635-7,612819,48087.0,NaN,NaN,NaN,129.159641,35.164474
1,23206623,미광장,NaN,O,숙박,O02,모텔/여관/여인숙,O02A01,모텔/여관/여인숙,I55112,...,2.611010e+24,NaN,부산광역시 중구 보수대로44번길 5,600074,48974.0,NaN,NaN,NaN,129.023668,35.100979
2,20418637,BHC치킨,동래점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2.626010e+24,NaN,부산광역시 동래구 동래로147번길 18,607020,47802.0,NaN,NaN,NaN,129.087156,35.205267
3,24659633,스텔라,NaN,D,소매,D05,의복의류,D05A01,일반의류,G47416,...,2.650010e+24,비치아파트,부산광역시 수영구 광안해변로 100,613751,48305.0,NaN,NaN,20,129.115397,35.143770
4,17174094,도란도란,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2.623010e+24,NaN,부산광역시 부산진구 가야대로482번길 29-3,614813,47327.0,NaN,NaN,NaN,129.024938,35.151645